### ISSUE TITLE
Annotated tags are ignored

### ISSUE THREAD

**Issue by davidolrik** [outofcoffee/since#2]
If you create an annotated version tag with a message like so:

```sh
git tag -m "Message" 0.2.0
```

The tag will **not** be considered when calculating the next tag.

So given the following commits where `0.2.0` is annotated, the calculated next version will be `0.2.0` because `0.2.0` is ignored and `0.1.0` is used as a starting point.

9f807d5 feat: Feature D
9f807d4 feat: Feature C (tag: 0.2.0)
9f807d3 feat: Feature B (tag: 0.1.0)
9f807d2 feat: Feature A
9f807d1 chore: Inital commit (tag: 0.0.1)

The next tag in this example should be `0.3.0`.

**Comment by outofcoffee** [comment]
Hi @davidolrik, thank you for raising this. This issue has been fixed in [v0.15.3](https://github.com/release-tools/since/releases).
